### ISSUE TITLE
minSdk

### ISSUE THREAD

**Issue by moisoni97** [TonnyL/Spark#2]
My minSdk is 16 and when I compile your library I got this message : 
`Suggestion: use a compatible library with a minSdk of at most 16, or increase this project's minSdk version to at least 19`

My question is: Will I have any problems using this library with minSdk 16?

I olso change the minSdk from the sampe app to ` minSdkVersion    : 14` and still works without any error messages when building project.

P.S. Nice library, thanks!

**Comment by TonnyL** [comment]
Hi, @moisoni97 

You could download Spark's source code, downgrade the minSDK version and implement whole project as module to your own project. Or just fork this repo, optimize the code, and publish it to Jcenter by yourself. 

In fact, I haven't test this library on devices whose SDK version are below 19, so I cannot guarantee that there is no compatibility problem. As for the reason why this library's minSDK version is so high(is it high?), see the image below. 
<img width="888" alt="screen shot 2018-10-23 at 11 33 42 am" src="https://user-images.githubusercontent.com/13329148/47333938-8dbaf800-d6b7-11e8-96f4-a8712602478a.png">
So I gave up those devices 😂.

Thx for your  approval. Happy coding 😉!

**Comment by TonnyL** [comment]
I will close this issue now, if you have any other question, reopen it or just file another new issue. 😉!
